package hw.weatherbit.homework;// Generated by Selenium IDE
import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.Matchers.containsString;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

@ExtendWith(SeleniumJupiter.class)
public class WebControllerSeleniumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testWebDriver() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(945, 1020));


    driver.findElement(By.name("city")).click();
    driver.findElement(By.name("city")).sendKeys("Aveiro");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();

    String value = driver.findElement(By.id("WeatherApiCalls")).getText();
    assertThat(value, containsString("1"));
    value = driver.findElement(By.id("GeolocationApiCalls")).getText();
    assertThat(value, containsString("1"));
    value = driver.findElement(By.id("weatherCacheUsage")).getText();
    assertThat(value, containsString("0"));
    value = driver.findElement(By.id("geolocatorCacheUsage")).getText();
    assertThat(value, containsString("0"));



    driver.findElement(By.name("city")).click();
    driver.findElement(By.name("city")).sendKeys("Porto");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();

    value = driver.findElement(By.id("WeatherApiCalls")).getText();
    assertThat(value, containsString("2"));
    value = driver.findElement(By.id("GeolocationApiCalls")).getText();
    assertThat(value, containsString("2"));
    value = driver.findElement(By.id("weatherCacheUsage")).getText();
    assertThat(value, containsString("0"));
    value = driver.findElement(By.id("geolocatorCacheUsage")).getText();
    assertThat(value, containsString("0"));

    driver.findElement(By.name("city")).click();
    driver.findElement(By.name("city")).sendKeys("Aveiro");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();

    value = driver.findElement(By.id("WeatherApiCalls")).getText();
    assertThat(value, containsString("2"));
    value = driver.findElement(By.id("GeolocationApiCalls")).getText();
    assertThat(value, containsString("2"));
    value = driver.findElement(By.id("weatherCacheUsage")).getText();
    assertThat(value, containsString("1"));
    value = driver.findElement(By.id("geolocatorCacheUsage")).getText();
    assertThat(value, containsString("1"));


    driver.get("http://localhost:8080/cache");
    List<WebElement> list = driver.findElements(By.xpath("//*[contains(text(),'Valid:')]"));
    assertThat(list.size(), equalTo(2));
  }
}



